name: mobisoft_inspection
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.10.0+5
  video_player: ^2.4.10
#  gallery_saver: ^2.3.2
  equatable: ^2.0.5
  flutter_screenutil: ^5.6.0
  country_code_picker: ^2.0.2
  phone_number: ^1.0.0
  telephony: ^0.2.0
  device_info_plus: 8.0.0
#  google_maps_flutter: ^2.2.3
  api_handler:
    git: { url: 'https://github.com/ardeshir-33033/api_helper.git', ref: main }
  location: ^4.4.0
  flutter_bloc: 8.1.1
  dotted_border: ^2.0.0+3
  get_it: ^7.2.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bdd_widget_test: ^1.4.3
  build_runner:
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
#  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
